FROM node:20-alpine
LABEL maintainer="Tomer Zait (realgam3) <realgam3@gmail.com>"

ARG USERNAME=app
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD true
ENV PUPPETEER_EXECUTABLE_PATH /usr/bin/chromium-browser
WORKDIR /usr/src/app
COPY package*.json .
COPY local.conf .

RUN set -eux; \
    \
    echo "@edge http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories; \
    echo "@edgecommunity http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories; \
    echo "@testing http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories; \
    \
    apk upgrade -U -a; \
    apk add --no-cache \
      xvfb@edge \
      libstdc++@edge \
      chromium@edge \
      harfbuzz@edge \
      nss@edge \
      freetype@edge \
      ttf-freefont@edge \
      font-noto-emoji@edge \
      wqy-zenhei@testing; \
    rm -rf /var/cache/*; \
    mkdir /var/cache/apk; \
    mv local.conf /etc/fonts/local.conf; \
    \
    npm install -g pm2; \
    npm install; \
    \
    adduser --disabled-password --no-create-home --gecos ${USERNAME} ${USERNAME}

COPY . .

USER ${USERNAME}
ENV HOME=/tmp

CMD [ "npm", "start" ]
