version: '2'

services:
  backend:
    build: backend
    ports:
      - "3000:3000"
    restart: always

  queue:
    image: rabbitmq:3.9.7-alpine
    expose:
      - "5672"
    restart: always

  bot:
    image: realgam3/puppeteer-bot:latest
    depends_on:
      - queue
    volumes:
      - "./bot/config.js:/usr/src/app/config.js"
    restart: always
